eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: "http://localhost:7001/eureka/"
  instance:
    appname: zuul-server

server:
  port: 80

spring:
  application:
    name: zuul-server
  zipkin:
    base-url: "http://localhost:9411/"
  sleuth:
    sampler:
      rate: 1


eureka-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
zuul:
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 10000
  routes:
    eureka-consumer.path: /liyq/**
  ignored-services: eureka-consumer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    routes:
      enabled: true
