eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: "http://localhost:7001/eureka/"
  instance:
    appname: provider

server:
  port: 81

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
spring:
  application:
    name: eureka-provider
  zipkin:
    base-url: "http://localhost:9411/"
    sleuth:
      sampler:
        rate: 1
  boot:
    admin:
      client:
        url: "http://localhost:8080/"

